# Generated by Django 5.2.8 on 2026-01-14 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contentblock',
            old_name='block_type',
            new_name='type',
        ),
        migrations.AlterField(
            model_name='contentblock',
            name='identifier',
            field=models.SlugField(),
        ),
        migrations.AlterUniqueTogether(
            name='contentblock',
            unique_together={('content', 'identifier', 'language')},
        ),
    ]
