# Generated by Django 5.2.8 on 2026-01-15 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_rename_block_type_contentblock_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentblock',
            name='image',
        ),
        migrations.AddField(
            model_name='contentblock',
            name='image_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
