# Generated by Django 5.2.8 on 2026-01-28 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_remove_contentblock_image_contentblock_image_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentblock',
            name='image_path',
        ),
        migrations.AddField(
            model_name='contentblock',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='content/'),
        ),
    ]
