# Generated by Django 5.2.8 on 2025-12-03 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='currency',
            new_name='default_currency',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='default_price',
        ),
        migrations.AddField(
            model_name='product',
            name='default_stock',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='sku',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
