# Generated by Django 5.2.8 on 2026-01-27 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_productimage_image_productimage_image_path_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='image_path',
        ),
        migrations.AddField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/images/'),
        ),
    ]
