# Generated by Django 5.2.8 on 2026-01-27 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_productimage_image_path_productimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartproduct',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartproduct',
            name='product_variant',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartProduct',
        ),
    ]
