# Generated by Django 5.2.8 on 2026-01-29 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_attribute_attributevalue_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['id'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['id']},
        ),
    ]
